ci: update check-code-quality.yml

diff --git a/.github/workflows/check-code-quality.yml b/.github/workflows/check-code-quality.yml
--- a/.github/workflows/check-code-quality.yml
+++ b/.github/workflows/check-code-quality.yml
@@ -27,8 +27,16 @@ jobs:
 
       - name: Run linters
         run: |
-          ruff check . > report.md || true
-          pyright     >> report.md || true
+          ruff check . > report.md
+          RUFF_EXIT_CODE=$?
+
+          pyright     >> report.md
+          PYRIGHT_EXIT_CODE=$?
+
+          if [ $RUFF_EXIT_CODE -ne 0 ] || [ $PYRIGHT_EXIT_CODE -ne 0 ]; then
+            echo "One of the linters failed"
+            exit 1
+          fi
           
       - name: Upload analysis report
         if: success()
